/** Represents a note object returned by the application API boundary. */
export interface NoteDto {
  /** Stable note identifier generated by the data layer. */
  id: string;
  /** Main note body using lightweight Markdown-compatible text. */
  content: string;
  /** Optional field identifier associated with the note. */
  fieldId?: string;
  /** Unix timestamp for note creation. */
  createdAt: number;
  /** Unix timestamp for the latest note update. */
  updatedAt: number;
  /** Tag names projected for UI display. */
  tags: string[];
}

/** Defines supported note list filters at the frontend API boundary. */
export interface NotesQuery {
  /** Optional full-text search keyword. */
  keyword?: string;
  /** Optional tag name used for filtering. */
  tag?: string;
  /** Optional field identifier used for filtering. */
  fieldId?: string;
}

/** Defines options supported by the recent notes endpoint. */
export interface RecentNotesQuery {
  /** Maximum number of recent notes to return. */
  limit?: number;
  /** Optional full note ID used as a pagination cursor. */
  noteUuid?: string;
}

/** Describes input required to create a note through the API boundary. */
export interface CreateNoteInput {
  /** Main note body using lightweight Markdown-compatible text. */
  content: string;
  /** Tag names parsed or selected by the user. */
  tags?: string[];
  /** Optional field name associated with the note. */
  field?: string;
  /** Optional role used when creating the note. */
  role?: string;
  /** Optional device identifier used for revision tracking. */
  deviceId?: string;
}

/** Describes input required to update a note through the API boundary. */
export interface UpdateNoteInput {
  /** New main note body. */
  content: string;
  /** Optional device identifier used for revision tracking. */
  deviceId?: string;
}

/** Represents structured error details returned by the backend. */
export interface ApiErrorBody {
  /** Machine-readable error code. */
  code: string;
  /** Human-readable error message. */
  message: string;
  /** Additional backend-specific error details. */
  details: Record<string, unknown>;
}

/** Represents the backend note database record shape. */
export interface NoteRecord {
  /** Stable note identifier. */
  id: string;
  /** Note body content. */
  content: string;
  /** Role that created the note. */
  role: string;
  /** Unix timestamp for note creation. */
  created_at: number;
  /** Unix timestamp for the latest note update. */
  updated_at: number;
  /** Optional field identifier for this note. */
  field_id?: string | null;
  /** Optional current revision identifier. */
  current_revision_id?: string | null;
  /** Optional archived timestamp. */
  archived_at?: number | null;
  /** Optional deleted timestamp. */
  deleted_at?: number | null;
}

/** Represents user-facing note metadata resolved by the backend. */
export interface NoteMetadata {
  /** Resolved tag names. */
  tags: string[];
  /** Role that created the note. */
  role: string;
  /** Optional resolved field name. */
  field?: string | null;
}

/** Represents the backend single-note response wrapper. */
export interface NoteResponse {
  /** Persisted note record. */
  note: NoteRecord;
  /** User-facing metadata for the note. */
  metadata: NoteMetadata;
}

/** Represents the backend list-notes response wrapper. */
export interface ListNotesResponse {
  /** Active note records. */
  notes: NoteRecord[];
}

/** Represents a backend tag database record. */
export interface TagRecord {
  /** Stable tag identifier. */
  id: string;
  /** Human-readable tag name. */
  name: string;
  /** Unix timestamp for tag creation. */
  created_at: number;
}

/** Represents the backend note-tags response wrapper. */
export interface ListNoteTagsResponse {
  /** Tags associated with a note. */
  tags: TagRecord[];
}

/** Represents a field object returned by the application API boundary. */
export interface FieldDto {
  /** Stable field identifier generated by the data layer. */
  id: string;
  /** Human-readable field name. */
  name: string;
  /** Unix timestamp for field creation. */
  createdAt: number;
}

/** Represents a backend field database record. */
export interface FieldRecord {
  /** Stable field identifier. */
  id: string;
  /** Human-readable field name. */
  name: string;
  /** Unix timestamp for field creation. */
  created_at: number;
}

/** Represents the backend list-fields response wrapper. */
export interface ListFieldsResponse {
  /** Field records ordered by name. */
  fields: FieldRecord[];
  /** Field names in the same order as records. */
  names: string[];
}
