/** Represents a note object returned by the application API boundary. */
export interface NoteDto {
  /** Stable note identifier generated by the data layer. */
  id: string;
  /** Main note body using lightweight Markdown-compatible text. */
  content: string;
  /** Optional field identifier associated with the note. */
  fieldId?: string;
  /** Unix timestamp for note creation. */
  createdAt: number;
  /** Unix timestamp for the latest note update. */
  updatedAt: number;
  /** Tag names projected for UI display. */
  tags: string[];
}

/** Defines supported note list filters at the frontend API boundary. */
export interface NotesQuery {
  /** Optional full-text search keyword. */
  keyword?: string;
  /** Optional tag name used for filtering. */
  tag?: string;
}

/** Describes input required to create a note through the API boundary. */
export interface CreateNoteInput {
  /** Main note body using lightweight Markdown-compatible text. */
  content: string;
  /** Tag names parsed or selected by the user. */
  tags?: string[];
}
