/** Represents a note object returned by the application API boundary. */
export interface NoteDto {
  /** Stable note identifier generated by the data layer. */
  id: string;
  /** Main note body using lightweight Markdown-compatible text. */
  content: string;
  /** Optional field identifier associated with the note. */
  fieldId?: string;
  /** Unix timestamp for note creation. */
  createdAt: number;
  /** Unix timestamp for the latest note update. */
  updatedAt: number;
  /** Tag names projected for UI display. */
  tags: string[];
}

/** Defines supported note list filters at the frontend API boundary. */
export interface NotesQuery {
  /** Optional full-text search keyword. */
  keyword?: string;
  /** Optional tag name used for filtering. */
  tag?: string;
  /** Optional field identifier used for filtering. */
  fieldId?: string;
}

/** Defines options supported by the recent notes endpoint. */
export interface RecentNotesQuery {
  /** Maximum number of recent notes to return. */
  limit?: number;
  /** Optional full note ID used as a pagination cursor. */
  noteUuid?: string;
}

/** Describes input required to create a note through the API boundary. */
export interface CreateNoteInput {
  /** Main note body using lightweight Markdown-compatible text. */
  content: string;
  /** Tag names parsed or selected by the user. */
  tags?: string[];
  /** Optional field name associated with the note. */
  field?: string;
  /** Optional role used when creating the note. */
  role?: string;
  /** Optional device identifier used for revision tracking. */
  deviceId?: string;
}

/** Describes input required to update a note through the API boundary. */
export interface UpdateNoteInput {
  /** New main note body. */
  content: string;
  /** Optional replacement tag names parsed from the note body. */
  tags?: string[];
  /** Optional field name update; null moves the note to inbox. */
  field?: string | null;
  /** Optional device identifier used for revision tracking. */
  deviceId?: string;
}

/** Represents structured error details returned by the backend. */
export interface ApiErrorBody {
  /** Machine-readable error code. */
  code: string;
  /** Human-readable error message. */
  message: string;
  /** Additional backend-specific error details. */
  details: Record<string, unknown>;
}

/** Represents the backend note database record shape. */
export interface NoteRecord {
  /** Stable note identifier. */
  id: string;
  /** Note body content. */
  content: string;
  /** Role that created the note. */
  role: string;
  /** Unix timestamp for note creation. */
  created_at: number;
  /** Unix timestamp for the latest note update. */
  updated_at: number;
  /** Optional field identifier for this note. */
  field_id?: string | null;
  /** Optional current revision identifier. */
  current_revision_id?: string | null;
  /** Optional archived timestamp. */
  archived_at?: number | null;
  /** Optional deleted timestamp. */
  deleted_at?: number | null;
}

/** Represents user-facing note metadata resolved by the backend. */
export interface NoteMetadata {
  /** Resolved tag names. */
  tags: string[];
  /** Role that created the note. */
  role: string;
  /** Optional resolved field name. */
  field?: string | null;
}

/** Represents the backend single-note response wrapper. */
export interface NoteResponse {
  /** Persisted note record. */
  note: NoteRecord;
  /** User-facing metadata for the note. */
  metadata: NoteMetadata;
}

/** Represents the backend list-notes response wrapper. */
export interface ListNotesResponse {
  /** Active note records. */
  notes: NoteRecord[];
}

/** Represents one server-local daily note count bucket. */
export interface DailyNoteCount {
  /** Calendar date in YYYY-MM-DD format. */
  date: string;
  /** Number of visible notes created on this date. */
  count: number;
}

/** Represents the backend daily note count response wrapper. */
export interface DailyNoteCountsResponse {
  /** Daily note counts ordered by date ascending. */
  days: DailyNoteCount[];
}

/** Represents a backend tag database record. */
export interface TagRecord {
  /** Stable tag identifier. */
  id: string;
  /** Human-readable tag name. */
  name: string;
  /** Unix timestamp for tag creation. */
  created_at: number;
}

/** Represents a tag object returned by the application API boundary. */
export interface TagDto {
  /** Stable tag identifier generated by the data layer. */
  id: string;
  /** Human-readable tag name. */
  name: string;
  /** Unix timestamp for tag creation. */
  createdAt: number;
}

/** Represents the backend note-tags response wrapper. */
export interface ListNoteTagsResponse {
  /** Tags associated with a note. */
  tags: TagRecord[];
}

/** Represents the backend list-tags response wrapper. */
export interface ListTagsResponse {
  /** Tag records ordered by name. */
  tags: TagRecord[];
  /** Tag names in the same order as records. */
  names: string[];
}

/** Represents a field object returned by the application API boundary. */
export interface FieldDto {
  /** Stable field identifier generated by the data layer. */
  id: string;
  /** Human-readable field name. */
  name: string;
  /** Unix timestamp for field creation. */
  createdAt: number;
}

/** Represents a backend field database record. */
export interface FieldRecord {
  /** Stable field identifier. */
  id: string;
  /** Human-readable field name. */
  name: string;
  /** Unix timestamp for field creation. */
  created_at: number;
}

/** Represents the backend list-fields response wrapper. */
export interface ListFieldsResponse {
  /** Field records ordered by name. */
  fields: FieldRecord[];
  /** Field names in the same order as records. */
  names: string[];
}

/** Represents synchronization configuration shown at the frontend boundary. */
export interface SyncConfigDto {
  /** Whether background Supabase synchronization is enabled. */
  enabled: boolean;
  /** Delay in seconds between background synchronization attempts. */
  intervalSeconds: number;
  /** Supabase project URL used by the backend REST client. */
  supabaseUrl: string;
  /** Whether a service role key is configured on the backend. */
  serviceRoleKeyConfigured: boolean;
}

/** Represents the backend synchronization configuration response shape. */
export interface SyncConfigResponse {
  /** Whether background Supabase synchronization is enabled. */
  enabled: boolean;
  /** Delay in seconds between background synchronization attempts. */
  interval_seconds: number;
  /** Supabase project URL used by the backend REST client. */
  supabase_url: string;
  /** Whether a service role key is configured on the backend. */
  service_role_key_configured: boolean;
}

/** Describes input required to persist synchronization settings. */
export interface UpdateSyncConfigInput {
  /** Whether background Supabase synchronization should be enabled. */
  enabled: boolean;
  /** Delay in seconds between background synchronization attempts. */
  intervalSeconds: number;
  /** Supabase project URL used by the backend REST client. */
  supabaseUrl: string;
  /** Optional new service role key; blank values do not overwrite existing keys. */
  serviceRoleKey?: string;
}

/** Represents the backend synchronization configuration update request shape. */
export interface UpdateSyncConfigRequest {
  /** Whether background Supabase synchronization should be enabled. */
  enabled: boolean;
  /** Delay in seconds between background synchronization attempts. */
  interval_seconds: number;
  /** Supabase project URL used by the backend REST client. */
  supabase_url: string;
  /** Optional new service role key. */
  service_role_key?: string | null;
}

/** Describes input used to test synchronization settings without saving them. */
export interface TestSyncConfigInput {
  /** Optional Supabase project URL candidate. */
  supabaseUrl?: string;
  /** Optional service role key candidate. */
  serviceRoleKey?: string;
}

/** Represents the backend synchronization configuration test request shape. */
export interface TestSyncConfigRequest {
  /** Optional Supabase project URL candidate. */
  supabase_url?: string | null;
  /** Optional service role key candidate. */
  service_role_key?: string | null;
}

/** Represents a sanitized synchronization configuration test result. */
export interface SyncConfigTestResultDto {
  /** Whether the Supabase REST endpoint accepted the test request. */
  ok: boolean;
  /** Sanitized test result message. */
  message: string;
}

/** Represents the backend synchronization configuration test response shape. */
export interface SyncConfigTestResponse {
  /** Whether the Supabase REST endpoint accepted the test request. */
  ok: boolean;
  /** Sanitized test result message. */
  message: string;
}

/** Represents a synchronization cursor shown in status views. */
export interface SyncStateDto {
  /** Workspace that owns this cursor. */
  workspaceId: string;
  /** Device that owns this cursor. */
  deviceId: string;
  /** Cursor direction or synchronization scope. */
  scope: string;
  /** Last processed change timestamp. */
  lastChangeCreatedAt: number;
  /** Last processed change identifier. */
  lastChangeId: string;
  /** Last successful sync timestamp. */
  lastSuccessAt?: number | null;
  /** Last failed sync timestamp. */
  lastErrorAt?: number | null;
  /** Last failed sync message. */
  lastErrorMessage?: string | null;
}

/** Represents the backend synchronization cursor response shape. */
export interface SyncStateResponse {
  /** Workspace that owns this cursor. */
  workspace_id: string;
  /** Device that owns this cursor. */
  device_id: string;
  /** Cursor direction or synchronization scope. */
  scope: string;
  /** Last processed change timestamp. */
  last_change_created_at: number;
  /** Last processed change identifier. */
  last_change_id: string;
  /** Last successful sync timestamp. */
  last_success_at?: number | null;
  /** Last failed sync timestamp. */
  last_error_at?: number | null;
  /** Last failed sync message. */
  last_error_message?: string | null;
}

/** Represents synchronization status shown at the frontend boundary. */
export interface SyncStatusDto {
  /** Whether synchronization is enabled. */
  enabled: boolean;
  /** Local synchronization cursor rows. */
  states: SyncStateDto[];
}

/** Represents the backend synchronization status response shape. */
export interface SyncStatusResponse {
  /** Whether synchronization is enabled. */
  enabled: boolean;
  /** Local synchronization cursor rows. */
  states: SyncStateResponse[];
}

/** Represents the result of one manual synchronization run. */
export interface SyncRunResultDto {
  /** Number of local changes pushed remotely. */
  pushed: number;
  /** Number of remote changes pulled locally. */
  pulled: number;
}

/** Represents the backend manual synchronization run response shape. */
export interface SyncRunResponse {
  /** Number of local changes pushed remotely. */
  pushed: number;
  /** Number of remote changes pulled locally. */
  pulled: number;
}
